version: '3'
services:

  workout-postgres:
    container_name: workout-postgres
    image: postgres:9.6
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: "Th!sI5N0t4Produc7ion!"
      POSTGRES_DB: workout

  workout-project:
    container_name: workout-project
    build: .
    volumes:
      - .:/opt/project
    ports:
      - 127.0.0.1:1337:1337
    depends_on:
      - workout-postgres
